# Form implementation generated from reading ui file 'photo.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Photo(object):
    def setupUi(self, Photo):
        Photo.setObjectName("Photo")
        Photo.resize(400, 300)
        self.label = QtWidgets.QLabel(parent=Photo)
        self.label.setGeometry(QtCore.QRect(10, 10, 381, 251))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("image-imageicon.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=Photo)
        self.pushButton.setGeometry(QtCore.QRect(0, 270, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Photo)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 270, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=Photo)
        self.lineEdit.setGeometry(QtCore.QRect(110, 270, 181, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(parent=Photo)
        self.label_2.setGeometry(QtCore.QRect(300, 270, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Photo)
        QtCore.QMetaObject.connectSlotsByName(Photo)

    def retranslateUi(self, Photo):
        _translate = QtCore.QCoreApplication.translate
        Photo.setWindowTitle(_translate("Photo", "Rename Photos"))
        self.pushButton.setText(_translate("Photo", "Next"))
        self.pushButton_2.setText(_translate("Photo", "Previous"))
        self.label_2.setText(_translate("Photo", "<html><head/><body><p align=\"center\">Photo 1/999</p></body></html>"))
