# Form implementation generated from reading ui file 'rename.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_renameselectfolder(object):
    def setupUi(self, renameselectfolder):
        renameselectfolder.setObjectName("renameselectfolder")
        renameselectfolder.resize(400, 300)
        self.label = QtWidgets.QLabel(parent=renameselectfolder)
        self.label.setGeometry(QtCore.QRect(0, 20, 401, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(38)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=renameselectfolder)
        self.groupBox.setGeometry(QtCore.QRect(20, 90, 151, 151))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(0, 40, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(parent=renameselectfolder)
        self.pushButton.setGeometry(QtCore.QRect(210, 90, 151, 151))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(parent=renameselectfolder)
        self.label_3.setGeometry(QtCore.QRect(230, 110, 121, 111))
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=renameselectfolder)
        self.label_4.setGeometry(QtCore.QRect(170, 150, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(renameselectfolder)
        QtCore.QMetaObject.connectSlotsByName(renameselectfolder)

    def retranslateUi(self, renameselectfolder):
        _translate = QtCore.QCoreApplication.translate
        renameselectfolder.setWindowTitle(_translate("renameselectfolder", "Rename Photos"))
        self.label.setText(_translate("renameselectfolder", "<html><head/><body><p><span style=\" font-size:24pt;\">Select a folder to start.</span></p></body></html>"))
        self.label_2.setText(_translate("renameselectfolder", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:700;\">Drag a folder here</span></p><p><span style=\" font-size:12pt; font-weight:700;\">📂</span></p></body></html>"))
        self.label_3.setText(_translate("renameselectfolder", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:700;\">Click to choose </span></p><p><span style=\" font-size:12pt; font-weight:700;\">a folder</span></p><p><span style=\" font-size:12pt; font-weight:700;\">📂</span></p></body></html>"))
        self.label_4.setText(_translate("renameselectfolder", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:700;\">OR</span></p></body></html>"))
